### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by jhouedanou** [payplug/payplug-magento2#55]
Hello.

We are having this weird issue on a Magento 2.3.4 installation when the plugin returns a "Bad Request" message to the server. 
It happens randomly.
Can you help us pinpoint the source of the issue? It's kind of urgent.

Thanks.

**Comment by juchi** [comment]
Hi,
We are going to need some more information in order to be able to help you and provide a fix if needed.
You can get in touch with the support team that will be able to gather the information they need and validate that your module installation is correct. You can contact the support via this page : https://www.payplug.com/contact
Regards,

**Comment by dan-payplug** [comment]
I am closing this issue because it has not any recent activity.
